config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  devise_for :users
  root to: 'pages#home'

  resources :bookings, only: [:new, :create, :show]
  get '/results', to: 'bookings#search'
  get '/activities', to: 'bookings#activities'
  get '/results_activities', to: 'bookings#search_activities'
  get '/roadbook', to: 'bookings#roadbook'
  get '/roadbook_confirmed', to: 'bookings#roadbook_confirmed'

  resources :orders, only: [:show, :create] do
    resources :payments, only: :new
  end

end

app/models/booking.rb
class Booking < ApplicationRecord

  belongs_to :user
  belongs_to :van

  has_many :booking_activities
  has_many :activities, through: :booking_activities

  has_many :booking_places
  has_many :places, through: :booking_places

  validates :start_date, :end_date, :total_price, presence: true

  monetize :price_cents

end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

def search

  @departure = params[:departure]
  result = Geocoder.search(params[:departure]).first.coordinates
  @departure_lat = result[0].to_s
  @departure_long = result[1].to_s

  @start_date = params[:start_date]
  @nights = params[:nights]
  @end_date = @start_date.to_date + @nights.to_i
  @sleeping_type = params[:place]
  @rythm = params[:rythm]
  @passengers = params[:passengers]
  @van_type = params[:van_type]

  # récupérer le van en fonction de passengers et van type
  @van = Van.find_van_from_criteria(@passengers, @van_type)
  @total_price = @van.price_per_night * @nights.to_i
  @booking = Booking.create(start_date: @start_date, end_date: @end_date, total_price: @total_price, user_id: current_user.id, van_id: @van.id, price: @total_price)

  # récupérer les places en fonction du sleeping type
  @radius = 50
  if @rythm == "relax"
    @radius = 40
  elsif @rythme == "moyen"
    @radius = 80
  else
    @radius = 200
  end

  @places_by_type = Place.find_place_from_criteria(@sleeping_type)
  @places_by_distance = Place.near([@departure_lat, @departure_long], @radius)
  @places_selection = @places_by_type & @places_by_distance

  @places = Place.all
  @markers = @places_selection.map do |place|
    {
      lat: place.latitude,
      lng: place.longitude,
      infoWindow: render_to_string(partial: "info_window", locals: { place: place })

    }
  end
  
  get_start_point
  @counter = 0
end


  def activities
    @booking = current_user.bookings.last
    @nights = (@booking.end_date - @booking.start_date).to_i
    @counter = 1
    @params = [params[:location1],
                params[:location2],
                params[:location3],
                params[:location4],
                params[:location5],
                params[:location6]]
    @saved_params = []
    @params.each_with_index do |param, index|
      if param
        @saved_params << param
        # return => ["38", "40", "41", "39"]
      end
    end
    @saved_params.each do |param|
      BookingPlace.create(place_id: param, booking_id: @booking.id)
    end
  end

  def search_activities

    #mapbox
    @booking = current_user.bookings.last
    @places = @booking.places
    @departure_lat = (43.300000).to_s
    @departure_long = (5.4).to_s
      @markers = @places.map do |place|
        {
          lat: place.latitude,
          lng: place.longitude,
          infoWindow: render_to_string(partial: "info_window", locals: { place: place })
        }
      end

    # récupérer les places en fonction de category
    @params = [params[:category_randonnée],
                params[:category_baignade],
                params[:category_villes],
                params[:category_culture],
                params[:category_détente],
                params[:category_animaux],
                params[:category_familial],
                params[:category_sensations],
                params[:category_gastronomie]]

    @categories = ["randonnée", "balnéaire", "villages", "culture", "détente", "animaux", "familial", "sensations", "gastronomie"]
    @choices = []
    @params.each_with_index do |param, index|
      if param == "1"
        @choices << @categories[index]
       end
    end

    @activities_selection = Activity.where(category: @choices)
    @activities_markers = @activities_selection.map do |activity|
      {
        lat: activity.latitude,
        lng: activity.longitude,
        infoWindow: render_to_string(partial: "info_window2", locals: { activity: activity })
      }
    end
    get_start_point
  end

  def roadbook
    # variables permettant d'afficher le van correspondant au booking
    @booking = current_user.bookings.last
    @van = @booking.van
    @total_price = @booking.total_price
    @nights = (@booking.end_date - @booking.start_date).to_i
    @start = Date.parse(@booking.start_date.to_s).strftime("%d/%m/%Y")
    @end = Date.parse(@booking.end_date.to_s).strftime("%d/%m/%Y")

    # créer des instances de BookingActivity
    # @booking = current_user.bookings.last
    @params = [params[:activity1],
                params[:activity2],
                params[:activity3],
                params[:activity4],
                params[:activity5],
                params[:activity6]]
    @saved_params = []
    @params.each_with_index do |param, index|
      if param
        @saved_params << param
        # return => ["38", "40", "41", "39"]
      end
    end
    @saved_params.each do |param|
      BookingActivity.create(activity_id: param, booking_id: @booking.id)
    end

    #afficher les emplacements
    @selected_places = @booking.booking_places
    @places_markers = @selected_places.map do |bp|
      {
        lat: bp.place.latitude,
        lng: bp.place.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { place: bp.place })
      }
    end

    #afficher les activities
    @selected_activities = @booking.booking_activities
    @activities_markers = @selected_activities.map do |ba|
      {
        lat: ba.activity.latitude,
        lng: ba.activity.longitude,
        infoWindow: render_to_string(partial: "info_window2", locals: { activity: ba.activity })
      }
    end

    get_start_point
  end

  def roadbook_confirmed
    @bookings = current_user.bookings.all
  end


  private


def booking_params
    params.require(:booking).permit(:start_date, :end_date, :total_price, :price)
end


  def get_start_point
    @start_point = [
      {
        lat: 43.296482,
        lng: 5.36978
      }
    ]
  end
end

app/views/bookings/_info_window.html.erb
<h2><%= place.name %></h2>
<p><%= place.address %></p>

app/views/bookings/_info_window2.html.erb
<h2><%= activity.name %></h2>
<p><%= activity.address %></p>

app/views/bookings/activities.html.erb
<h2 class="subtitle-green text-center mt-4">Sélectionnez 3 thèmes</h2>


<%= form_with(url: "/results_activities", method: "get", local: true) do |f| %>


        <div class="radio-group mt-4" id="first-radio">
            <div class="radio-option">
                <%= f.check_box :category_randonnée, class: "radio" %>
                <%= f.label :category_randonnée, cl_image_tag('https://res.cloudinary.com/df0stqosw/image/upload/v1616257443/Samba/Activities/randonnee.png_mdchoh.png') %>
                <%= f.label :category_randonnée, "Randonnée"%>
            </div>
            <div class="radio-option">
                <%= f.check_box :category_culture, class: "radio" %>
                <%= f.label :category_culture, cl_image_tag('https://res.cloudinary.com/df0stqosw/image/upload/v1616257443/Samba/Activities/culture.png_sy0g7x.png') %>
                <%= f.label :category_culture, "Culture" %>
            </div>
            <div class="radio-option">
                <%= f.check_box  :category_baignade, class: "radio" %>
                <%= f.label :category_baignade, cl_image_tag('https://res.cloudinary.com/df0stqosw/image/upload/v1616257443/Samba/Activities/swim.png_whjwiz.png') %>
                <%= f.label :category_baignade, "Baignade" %>
            </div>
        </div>
        <div class="radio-group">
            <div class="radio-option">
                <%= f.check_box :category_détente, class: "radio" %>
                <%= f.label :category_détente, cl_image_tag('https://res.cloudinary.com/df0stqosw/image/upload/v1616257443/Samba/Activities/d%C3%A9tente.png_fywhkd.png')%>
                <%= f.label :category_détente, "Détente"%>
            </div>
            <div class="radio-option">
                <%= f.check_box  :category_animaux, class: "radio" %>
                <%= f.label :category_animaux, cl_image_tag('https://res.cloudinary.com/df0stqosw/image/upload/v1616258767/Samba/Activities/animaux.png_i6vacg.png') %>
                <%= f.label :category_animaux, "Animaux"%>
            </div>
            <div class="radio-option">
                <%= f.check_box :category_familial, class: "radio" %>
                <%= f.label :category_familial, cl_image_tag('https://res.cloudinary.com/df0stqosw/image/upload/v1616257443/Samba/Activities/famille.png_sdo0hy.png') %>
                <%= f.label :category_familial, "Familial"%>
            </div>
        </div>
        <div class="radio-group">
            <div class="radio-option">
                <%= f.check_box  :category_sensations, class: "radio" %>
                <%= f.label :category_sensations, cl_image_tag('https://res.cloudinary.com/df0stqosw/image/upload/v1616257443/Samba/Activities/sensations.png_ts1mfg.png') %>
                <%= f.label :category_sensations, "Sensations" %>
            </div>
            <div class="radio-option">
                <%= f.check_box  :category_villes, class: "radio" %>
                <%= f.label :category_villes, cl_image_tag('https://res.cloudinary.com/df0stqosw/image/upload/v1616257442/Samba/Activities/village.png_rxjzcr.png') %>
                <%= f.label :category_villes, "Villes et villages" %>
            </div>
            <div class="radio-option">
                <%= f.check_box  :category_gastronomie, class: "radio" %>
                <%= f.label :category_gastronomie, cl_image_tag('https://res.cloudinary.com/df0stqosw/image/upload/v1616257443/Samba/Activities/gastronomie.png_tc5q0f.png') %>
                <%= f.label :category_gastronomie, "Gastronomie" %>
            </div>
        </div>

        <div class="text-center my-4">
            <%= f.submit "Voir les activités", class: "btn-samba" %>
        </div>

    <% end %>

</div>

app/views/bookings/roadbook.html.erb
<h2 class="subtitle-green">Mon véhicule</h2>

<%# affichage du van sélectionné %>

<div class="card-van">
    <div>
        <%= cl_image_tag @van.photo.key, class: "card-van-img" %>
    </div>

    <div class="van-card-price">
        <p><strong><%= @total_price %>€</strong> pour <%= @nights %> nuits</p>
    </div>

    <p class="van-card-name"><%= @van.name %></p>
    <p class="van-card-passengers" id="passengers-roadbook">Capacité: <%= @van.passengers %> personnes</p>
    <p class="van-card-date">Du <%= @start %> au <%= @end %> </p>
    <p class="van-card-description"><%= @van.description %></p>
</div>

<%# affichage de la map %>
<div id="map"
  style="width: 100%; height: 500px;"
  data-places="<%= @places_markers.to_json %>"
  data-activities="<%= @activities_markers.to_json %>"
  data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
  data-start="<%= @start_point.to_json %>"
  data-trace="true">
</div>


<%# affichage des emplacements %>
<h2 class="subtitle-green mt-2">Mes emplacements</h2>
  <% @selected_places.each do |selection| %>
    <div class="card-place">
      <%= cl_image_tag selection.place.photo.key, class: "card-place-img" %>
        <div class="card-place-infos">
          <p class="place-card-name"><%= selection.place.name %></p>
          <p class="place-card-address"><%= selection.place.address %></p>
          <p class="place-card-description"><%= selection.place.description.first(80) %>...</p>
            <div class="d-flex justify-content-end w-100">
              <%= image_tag "eye-samba.svg", class:"modal-button", data:{toggle: "modal", target:"#place-#{selection.place.id}"} %>
            </div>
              <div class="modal fade" id="place-<%= selection.place.id %>" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog">
                      <%= cl_image_tag selection.place.photo.key, class: "modal-img" %>
                  <div class="modal-content">
                    <p class="modal-title" ><%= selection.place.name %></p>
                    <p class="place-card-address"><%= selection.place.address %></p>
                    <p class="place-card-description"><%= selection.place.description %></p>
                  </div>
                </div>
              </div>
        </div>
    </div>
<% end %>

<%# affichage des activites %>
<h2 class="subtitle-green">Mes activités</h2>
  <% @selected_activities.each do |selection| %>
    <div class="card-activity">
      <%= cl_image_tag selection.activity.photo.key, class: "card-activity-img" %>
        <div class="card-activity-infos">
          <p class="activity-card-name"><%= selection.activity.name %></p>
          <p class="activity-card-address"><%= selection.activity.address %></p>
          <p class="activity-card-description"><%= selection.activity.description.first(80) %>...</p>
            <div class="d-flex justify-content-end w-100">
              <%= image_tag "eye-samba.svg", class:"modal-button", data:{toggle: "modal", target:"#activity-#{selection.activity.id}"} %>
            </div>
              <div class="modal fade" id="activity-<%= selection.activity.id %>" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog">
                      <%= cl_image_tag selection.activity.photo.key, class: "modal-img" %>
                      <div class="modal-content">
                        <p class="modal-title" ><%= selection.activity.name %></p>
                        <p class="activity-card-address"><%= selection.activity.address %></p>
                        <p class="activity-card-description"><%= selection.activity.description %></p>
                      </div>
                </div>
              </div>
        </div>
    </div>
  <% end %>

  <%# bouton vers le paiement %>

  <%= form_tag orders_path do %>
  <%= hidden_field_tag 'booking_id', @booking.id %>
  <div class="text-center mb-4">
    <%= submit_tag 'Valider et payer', class: 'btn-samba' %>
  </div>
<% end %>

app/views/bookings/roadbook_confirmed.html.erb
<h2 class="subtitle-green">Mes roadbooks</h2>

<% @bookings.each do |booking| %>
    <div class="roadbook">
        <div class="card-van">
            <div>
                <%= cl_image_tag booking.van.photo.key, class: "card-van-img" %>
            </div>
            <div class="van-card-price">
                <p><strong><%= booking.total_price %>€</strong> pour <%= (booking.end_date - booking.start_date).to_i %> nuits</p>
            </div>

            <p class="van-card-name"><%= booking.van.name %></p>
            <p class="van-card-passengers">Capacité: <%= booking.van.passengers %> personnes</p>
            <p class="van-card-date">Du <%= Date.parse(booking.start_date.to_s).strftime("%d/%m/%Y") %> au <%= Date.parse(booking.end_date.to_s).strftime("%d/%m/%Y") %> </p>
        </div>
        <% booking.booking_places.each do |bookingplace| %>
            <div class="d-flex">
                <div class="roadbook-small">
                    <%= cl_image_tag bookingplace.place.photo.key %>
                </div>
                <div class="roadbook-small">
                <p><strong><%= bookingplace.place.name %></strong></p>
                <p><%= bookingplace.place.address %></p>
                </div>
            </div>
        <% end %>
        <% booking.booking_activities.each do |bookingactivity| %>
            <div class="d-flex">
                <div class="roadbook-small">
                    <%= cl_image_tag bookingactivity.activity.photo.key %>
                </div>
                <div class="roadbook-small">
                <p><strong><%= bookingactivity.activity.name %></strong></p>
                <p><%= bookingactivity.activity.address %></p>
                </div>
            </div>
        <% end %>
    </div>
<% end %>

app/views/bookings/search.html.erb
<h2 class="subtitle-green">Mon véhicule</h2>

<%# affichage du van sélectionné %>

<div class="card-van">
    <div>
        <%= cl_image_tag @van.photo.key, class: "card-van-img" %>
    </div>

    <div class="van-card-price">
        <p><strong><%= @van.price_per_night * @nights.to_i %>€</strong> pour <%= @nights %> nuits</p>
    </div>

    <p class="van-card-name"><%= @van.name %></p>
    <p class="van-card-passengers">Capacité: <%= @van.passengers %> personnes</p>
    <p class="van-card-description"><%= @van.description %></p>
</div>

<%# Affichage de la carte %>

<h2 class="subtitle-green">Mes emplacements</h2>

<div id="map"
    style="width: 100%; height: 400px;"
    data-places="<%= @markers.to_json %>"
    data-activities="[]"
    data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
    data-start="<%= @start_point.to_json %>">
</div>

<%# Affichage de la liste (vide au départ) de sélection %>
<h2 class="subtitle-green mt-3">Ma sélection</h2>
<ul id="p-selection">
  <% @nights.to_i.times do %>
    <li class="first">Nuit <%= @counter += 1 %></li>
    <li class="empty"></li>
  <% end %>
</ul>
<%# Affichage des suggestions d'emplacements %>
    <br>
<h2 class="subtitle-green mt-n3">Mes suggestions</h2>
  <ul id="p-suggestions">
    <% @places_selection.each do |place| %>
      <li class="swap" data-place-id="<%=place.id%>">
        <div class="card-place">
          <%= cl_image_tag place.photo.key, class: "card-place-img" %>
          <div class="card-place-infos">
            <p class="place-card-name"><%= place.name %></p>
            <p class="place-card-address"><%= place.address %></p>
            <p class="place-card-description"><%= place.description.first(80) %>...</p>
            <div class="d-flex justify-content-end w-100">
              <%= image_tag "eye-samba.svg", class:"modal-button", data:{toggle: "modal", target:"#place-#{place.id}"} %>
            </div>
              <div class="modal fade" id="place-<%= place.id %>" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog">
                      <%= cl_image_tag place.photo.key, class: "modal-img" %>
                  <div class="modal-content">
                      <p class="modal-title" ><%= place.name %></p>
                      <p class="place-card-address"><%= place.address %></p>
                      <p class="place-card-description"><%= place.description %></p>
                  </div>
                </div>
              </div>
          </div>
        </div>
      </li>
    <% end %>
  </ul>
</div>

<%# Bouton submit %>
<div class="text-center">
  <button class="btn-samba mb-4" id="places-select">Valider mes emplacements</button>
</div>

app/views/bookings/search_activities.html.erb
<%# Affichage de la carte %>
<div id="map"
  style="width: 100%; height: 500px;"
  data-places="<%= @markers.to_json %>"
  data-activities="<%= @activities_markers.to_json %>"
  data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
  data-start= "<%= @start_point.to_json %>"
  data-trace="true">
</div>
<%# Affichage de la liste (vide au départ) de sélection d'activités %>
<h2 class="subtitle-green mt-3">Mes activités</h2>
<ul id="a-selection">
    <li class="empty-activities"></li>
</ul>

<%# Affichage des suggestions d'activités %>
<h2 class="subtitle-green">Suggestions</h2>
  <ul id="a-suggestions">
    <% @activities_selection.each do |activity| %>
      <li class="swap" data-activities-id="<%=activity.id%>" >
        <div class="card-activity">
          <%= cl_image_tag activity.photo.key, class: "card-activity-img" %>
          <div class="card-activity-infos">
            <p class="activity-card-name"><%= activity.name %></p>
            <p class="activity-card-address"><%= activity.address %></p>
            <p class="activity-card-description"><%= activity.description.first(80) %>...</p>
            <div class="d-flex justify-content-end w-100">
              <%= image_tag "eye-samba.svg", class:"modal-button", data:{toggle: "modal", target:"#activity-#{activity.id}"} %>
            </div>
              <div class="modal fade" id="activity-<%= activity.id %>" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog">
                      <%= cl_image_tag activity.photo.key, class: "modal-img" %>
                  <div class="modal-content">
                      <p class="modal-title" ><%= activity.name %></p>
                      <p class="activity-card-address"><%= activity.address %></p>
                      <p class="activity-card-description"><%= activity.description %></p>
                  </div>
                </div>
              </div>
          </div>
        </div>
      </li>
    <% end %>
  </ul>

<%# Bouton submit %>
<div class="text-center">
  <button class="btn-samba mb-4" id="activities-select">Valider mes activités</button>
</div>