config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  devise_for :users
  root to: 'pages#home'

  resources :bookings, only: [:new, :create, :show]
  get '/results', to: 'bookings#search'
  get '/activities', to: 'bookings#activities'
  get '/results_activities', to: 'bookings#search_activities'
  get '/roadbook', to: 'bookings#roadbook'
  get '/roadbook_confirmed', to: 'bookings#roadbook_confirmed'

  resources :orders, only: [:show, :create] do
    resources :payments, only: :new
  end

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :booking

  monetize :amount_cents

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
    def create
        booking = Booking.find(params[:booking_id])
        order  = Order.create!(booking: booking, amount: booking.price, state: 'pending', user: current_user)

        session = Stripe::Checkout::Session.create(
            payment_method_types: ['card'],
            line_items: [{
            name: booking.van.name,
            amount: booking.price_cents,
            currency: 'eur',
            quantity: 1
            }],
            success_url: order_url(order),
            cancel_url: order_url(order)
        )

        order.update(checkout_session_id: session.id)
        redirect_to new_order_payment_path(order)
    end

    def show
        @order = current_user.orders.find(params[:id])
        
    end
end

app/views/orders/show.html.erb
    <h2 class="subtitle-green mt-5 mb-4">Votre séjour en van est confirmé!</h2>
    <p>Nous venons d'envoyer un email à <%= current_user.email %> pour vous donner les détails pratiques.</p>
    <p>Samba vous remercie!<p>

    <div class="text-center my-4">
        <%= link_to 'Accéder à mes roadbooks', roadbook_confirmed_path, class: 'btn-samba py-2', id: 'roadbook-btn' %>
    </div>

    <div id="space"></div>

    